# Generated by Django 3.2.9 on 2021-11-28 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('serviceowners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('Place', 'Place'), ('Food', 'Food'), ('Clothe & Shoe', 'Clotheandshoe'), ('Material', 'Material')], default='Material', max_length=50)),
                ('unit_price', models.CharField(max_length=100)),
                ('photo_main', models.ImageField(upload_to='services/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='services/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='services/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='services/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='services/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='services/%Y/%m/%d/')),
                ('photo_6', models.ImageField(blank=True, upload_to='services/%Y/%m/%d/')),
                ('photo_7', models.ImageField(blank=True, upload_to='services/%Y/%m/%d/')),
                ('photo_8', models.ImageField(blank=True, upload_to='services/%Y/%m/%d/')),
                ('photo_9', models.ImageField(blank=True, upload_to='services/%Y/%m/%d/')),
                ('photo_10', models.ImageField(blank=True, upload_to='services/%Y/%m/%d/')),
                ('photo_11', models.ImageField(blank=True, upload_to='services/%Y/%m/%d/')),
                ('photo_12', models.ImageField(blank=True, upload_to='services/%Y/%m/%d/')),
                ('photo_13', models.ImageField(blank=True, upload_to='services/%Y/%m/%d/')),
                ('photo_14', models.ImageField(blank=True, upload_to='services/%Y/%m/%d/')),
                ('photo_15', models.ImageField(blank=True, upload_to='services/%Y/%m/%d/')),
                ('photo_16', models.ImageField(blank=True, upload_to='services/%Y/%m/%d/')),
                ('photo_17', models.ImageField(blank=True, upload_to='services/%Y/%m/%d/')),
                ('photo_18', models.ImageField(blank=True, upload_to='services/%Y/%m/%d/')),
                ('photo_19', models.ImageField(blank=True, upload_to='services/%Y/%m/%d/')),
                ('photo_20', models.ImageField(blank=True, upload_to='services/%Y/%m/%d/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='serviceowners.serviceowner')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
