# Generated by Django 3.2.9 on 2021-12-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
        migrations.AddField(
            model_name='service',
            name='wilaya',
            field=models.CharField(choices=[('All Willaya', 'Allwilaya'), ('Adrar', 'Adrar'), ('Chlef', 'Chlef'), ('Laghouat', 'Laghouat'), ('Oum El Bouaghi', 'Oumelbouaghi'), ('Batna', 'Batna'), ('Béjaïa', 'Bejaia'), ('Biskra', 'Biskra'), ('Béchar', 'Bechar'), ('Blida', 'Blida'), ('Bouira', 'Bouira'), ('Tamanrasset', 'Tamanrasset'), ('Tébessa', 'Tebessa'), ('Tlemcen', 'Tlemcen'), ('Tiaret', 'Tiaret'), ('Tizi Ouzou', 'Tiziouzou'), ('Alger', 'Alger'), ('Djelfa', 'Djelfa'), ('Jijel', 'Jijel'), ('Sétif', 'Setif'), ('Saïda', 'Saida'), ('Skikda', 'Skikda'), ('Sidi Bel Abbès', 'Sidibelabbes'), ('Annaba', 'Annaba'), ('Guelma', 'Guelma'), ('Constantine', 'Constantine'), ('Médéa', 'Medea'), ('Mostaganem', 'Mostaganem'), ("M'Sila", 'Msila'), ('Mascara', 'Mascara'), ('Ouargla', 'Ouargla'), ('Oran', 'Oran'), ('El Bayadh', 'Elbayadh'), ('Illizi', 'Illizi'), ('Bordj Bou Arreridj', 'Bordjbouarreridj'), ('Boumerdès', 'Boumerdes'), ('El Tarf', 'Eltarf'), ('Tindouf', 'Tindouf'), ('Tissemsilt', 'Tissemsilt'), ('El Oued', 'Eloued'), ('Khenchela', 'Khenchela'), ('Souk Ahras', 'Soukahras'), ('Tipaza', 'Tipaza'), ('Mila', 'Mila'), ('Aïn Defla', 'Aindefla'), ('Naâma', 'Naama'), ('Aïn Témouchent', 'Aintemouchent'), ('Ghardaïa', 'Ghardaia'), ('Relizane', 'Relizane'), ('Timimoun', 'Timimoun'), ('Bordj Badji Mokhtar', 'Bordjbadjimokhtar'), ('Ouled Djellal', 'Ouleddjellal'), ('Béni Abbès', 'Beniabbes'), ('In Salah', 'Insalah'), ('In Guezzam', 'Inguezzam'), ('Touggourt', 'Touggourt'), ('Djanet', 'Djanet'), ("El M'Ghair", 'Elmghair'), ('El Meniaa', 'Elmeniaa')], default='All Willaya', max_length=90),
        ),
        migrations.AlterModelTable(
            name='service',
            table=None,
        ),
    ]
